"""empty message

Revision ID: 34dcdb7a7d9d
Revises: fee9ddade32e
Create Date: 2021-10-08 21:31:34.973257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34dcdb7a7d9d'
down_revision = 'fee9ddade32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'tag_id')
    op.drop_table('tags')
    # ### end Alembic commands ###
