"""empty message

Revision ID: 0608952aac7c
Revises: c8aa87328d15
Create Date: 2021-11-26 22:11:25.245922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0608952aac7c'
down_revision = 'c8aa87328d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
