"""empty message

Revision ID: 82ecd2830bc9
Revises: 34dcdb7a7d9d
Create Date: 2021-10-10 02:24:44.064437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ecd2830bc9'
down_revision = '34dcdb7a7d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('video_src', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('image_src', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'image_src')
    op.drop_column('projects', 'video_src')
    # ### end Alembic commands ###
