"""empty message

Revision ID: 8ad10566630d
Revises: 754c71f92590
Create Date: 2021-10-14 13:31:48.653165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad10566630d'
down_revision = '754c71f92590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('campaign', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'campaign')
    # ### end Alembic commands ###
