"""empty message

Revision ID: 1b635c903c11
Revises: 06aac22a2942
Create Date: 2021-12-23 01:57:45.352576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b635c903c11'
down_revision = '06aac22a2942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
