"""empty message

Revision ID: 7bde902c5577
Revises: 542d75ab23a2
Create Date: 2022-01-10 08:29:52.776837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bde902c5577'
down_revision = '542d75ab23a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
